name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['master']

jobs:

  
  docker_push_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          pwd
          docker build -t davidjay2111/demo-node-repo:${{env.GITHUB_RUN_NUMBER}} ../../.
          docker push davidjay2111/demo-node-repo:${{env.GITHUB_RUN_NUMBER}}
       
        
